version: "3.3"
services:
  client-nginx:
    build:
      context: ./
    mem_limit: 50m
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        compress: "true"
