version: "3.3"
services:
  root-nginx:
    image: nginx:latest
    mem_limit: 50m
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./root-nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        compress: "true"
  client-nginx:
    build:
      context: ./client
    mem_limit: 50m
    restart: always
    volumes:
      - ./client-nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - REACT_APP_TG_BOT_NAME=${TG_BOT_NAME}
      - REACT_APP_TG_MK_ADMIN_USER=${TG_MK_ADMIN_USER}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
        compress: "true"
  beowolf-backend:
    image: beowolf
    build:
      context: ./backend
    restart: always
    mem_limit: 512m
    environment:
      - TZ=UTC
      - TG_TOKEN=${TG_TOKEN}
      - CLASS_RPS=${CLASS_RPS}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - DB_MAX_CONNECTIONS=${DB_MAX_CONNECTIONS}
      - DEBUG_MODE=${DEBUG_MODE}
      - MY_CLASS_API_KEY=${MY_CLASS_API_KEY}
      - TG_LINK_ATTRIBUTE_ID=${TG_LINK_ATTRIBUTE_ID}
      - TG_MK_ADMIN_USER=${TG_MK_ADMIN_USER}
      - MK_MASTER_PASSWORD=${MK_MASTER_PASSWORD}
      - MK_SITE_ORIGIN=${MK_SITE_ORIGIN}
      - TG_BOT_NAME=${TG_BOT_NAME}
      - LK_SITE_ORIGIN=${LK_SITE_ORIGIN}
      - GOOGLE_SHEETS_ID=${GOOGLE_SHEETS_ID}
      - GOOGLE_SHEETS_API_KEY=${GOOGLE_SHEETS_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - AMPLITUDE_API_KEY=${AMPLITUDE_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
        compress: "true"
