name: CI
on: [ push ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Deploy_env
    steps:
      - uses: actions/checkout@main
      - name: Push to server
        uses: appleboy/ssh-action@master
        env:
          CLASS_RPS: ${{ vars.CLASS_RPS }}
          SERVER_PORT: ${{ vars.SERVER_PORT }}
          DEBUG_MODE: 1
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          MY_CLASS_API_KEY: ${{ secrets.MY_CLASS_API_KEY }}
          DB_MAX_CONNECTIONS: 50
          TG_LINK_ATTRIBUTE_ID: ${{ secrets.TG_LINK_ATTRIBUTE_ID }}
          TG_MK_ADMIN_USER: ${{ secrets.TG_MK_ADMIN_USER }}
          TG_BOT_NAME: ${{ vars.TG_BOT_NAME }}
          LK_SITE_ORIGIN: ${{ vars.LK_SITE_ORIGIN }}
          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
          MIN_NOTIFY_WORDS_COUNT: ${{ vars.MIN_NOTIFY_WORDS_COUNT }}
          NOTIFY_REPEAT_TIME: ${{ vars.NOTIFY_REPEAT_TIME }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: CLASS_RPS,SERVER_PORT,DEBUG_MODE,TG_TOKEN,DB_HOST,DB_USER,DB_PASS,DB_PORT,DB_MAX_CONNECTIONS,MY_CLASS_API_KEY,TG_LINK_ATTRIBUTE_ID,TG_MK_ADMIN_USER,TG_BOT_NAME,LK_SITE_ORIGIN,GOOGLE_SHEETS_ID,GOOGLE_SHEETS_API_KEY,SESSION_SECRET,AMPLITUDE_API_KEY,MIN_NOTIFY_WORDS_COUNT,NOTIFY_REPEAT_TIME,CLASS_RPS,SERVER_PORT
          script: |
            cd ${{ vars.PROJECT_PATH }}
            git pull https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com/virginia1066/platform1.git main
            docker-compose build
            docker-compose up -d
