name: CI
on: [ push ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Deploy_env
    steps:
      - uses: actions/checkout@main
      - name: Push to server
        uses: appleboy/ssh-action@master
        env:
          CLASS_RPS: 7
          SERVER_PORT: 3000
          DEBUG_MODE: 1
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          MY_CLASS_API_KEY: ${{ secrets.MY_CLASS_API_KEY }}
          DB_MAX_CONNECTIONS: 50
          TG_LINK_ATTRIBUTE_ID: ${{ secrets.TG_LINK_ATTRIBUTE_ID }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: CLASS_RPS,SERVER_PORT,DEBUG_MODE,TG_TOKEN,DB_HOST,DB_USER,DB_PASS,DB_PORT,DB_MAX_CONNECTIONS,MY_CLASS_API_KEY,TG_LINK_ATTRIBUTE_ID
          script: |
            cd ${{ vars.PROJECT_PATH }}
            git pull https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com/virginia1066/platform1.git main
            cd ./backend
            docker-compose build
            docker-compose up -d
